{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[2020-01-23 11:24:26 +0000] [16035] [INFO] Starting gunicorn 20.0.4\n",
      "[2020-01-23 11:24:26 +0000] [16035] [INFO] Listening at: http://127.0.0.1:5000 (16035)\n",
      "[2020-01-23 11:24:26 +0000] [16035] [INFO] Using worker: sync\n",
      "[2020-01-23 11:24:26 +0000] [16038] [INFO] Booting worker with pid: 16038\n",
      "2020/01/23 11:43:13 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/model-versions/search [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/mlflow/server/handlers.py\", line 137, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/mlflow/server/handlers.py\", line 581, in _search_model_versions\n",
      "    model_versions_detailed = _get_model_registry_store().search_model_versions(\n",
      "AttributeError: 'NoneType' object has no attribute 'search_model_versions'\n",
      "2020/01/23 13:24:05 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/model-versions/search [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/mlflow/server/handlers.py\", line 137, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/mlflow/server/handlers.py\", line 581, in _search_model_versions\n",
      "    model_versions_detailed = _get_model_registry_store().search_model_versions(\n",
      "AttributeError: 'NoneType' object has no attribute 'search_model_versions'\n",
      "2020/01/23 13:24:33 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/registered-models/list [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/mlflow/server/handlers.py\", line 137, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/mlflow/server/handlers.py\", line 498, in _list_registered_models\n",
      "    registered_models_detailed = _get_model_registry_store().list_registered_models()\n",
      "AttributeError: 'NoneType' object has no attribute 'list_registered_models'\n",
      "2020/01/23 13:24:35 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/model-versions/search [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/mlflow/server/handlers.py\", line 137, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/mlflow/server/handlers.py\", line 581, in _search_model_versions\n",
      "    model_versions_detailed = _get_model_registry_store().search_model_versions(\n",
      "AttributeError: 'NoneType' object has no attribute 'search_model_versions'\n",
      "2020/01/24 15:48:30 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/model-versions/search [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/mlflow/server/handlers.py\", line 137, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/pedro/anaconda3/envs/py36/lib/python3.6/site-packages/mlflow/server/handlers.py\", line 581, in _search_model_versions\n",
      "    model_versions_detailed = _get_model_registry_store().search_model_versions(\n",
      "AttributeError: 'NoneType' object has no attribute 'search_model_versions'\n"
     ]
    }
   ],
   "source": [
    "!mlflow ui"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:py36]",
   "language": "python",
   "name": "conda-env-py36-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
